# -*- coding: utf-8 -*-
from odoo import api, fields, models, _
from odoo.exceptions import UserError


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    stock_project_id = fields.Many2one(
        'project.project', string="Stock Project", copy=False, index='btree_not_null',
        help="Project automatically generated by this Sales Order for Storable products "
             "configured with 'Create Project on Order'.",
    )
    stock_project_count = fields.Integer(
        string="Stock Projects", compute='_compute_stock_project_count')

    @api.depends('stock_project_id', 'order_line.stock_task_id')
    def _compute_stock_project_count(self):
        for order in self:
            projects = order.stock_project_id | order.order_line.stock_task_id.project_id
            order.stock_project_count = len(projects)

    def _action_confirm(self):
        result = super()._action_confirm()
        self._stock_generate_project_and_tasks()
        return result

    def _stock_generate_project_and_tasks(self):
        """ Generate projects/tasks for Storable product lines, after the standard
            sale/inventory confirmation flow has been executed by super().
        """
        for order in self:
            lines = order.order_line.filtered(
                lambda l: l.product_id.detailed_type == 'product'
                and l.product_id.stock_project_tracking != 'no')
            if not lines:
                continue
            order = order.sudo().with_company(order.company_id)
            lines = lines.sudo().with_company(order.company_id)
            need_project = any(
                l.product_id.stock_project_tracking in ('project', 'project_task')
                for l in lines)
            # Maximum one auto project per Sales Order
            project = order._stock_get_or_create_project() if need_project else False
            for line in lines:
                tracking = line.product_id.stock_project_tracking
                if tracking == 'project':
                    continue
                if tracking == 'task':
                    project = line._stock_get_product_project()
                line._stock_create_task(project)

    def _stock_get_or_create_project(self):
        """ Create (or reuse) the single project generated by this Sales Order. """
        self.ensure_one()
        if self.stock_project_id:
            return self.stock_project_id
        project = self.env['project.project'].create({
            'name': "%s - %s" % (self.name, self.partner_id.display_name or self.partner_id.name),
            'partner_id': self.partner_id.id,
            'company_id': self.company_id.id,
            'active': True,
        })
        if not project.type_ids:
            project.type_ids = self.env['project.task.type'].create([{
                'name': name,
                'fold': fold,
                'sequence': sequence,
            } for name, fold, sequence in [
                (_('To Do'), False, 5),
                (_('In Progress'), False, 10),
                (_('Done'), True, 15),
                (_('Canceled'), True, 20),
            ]])
        self.stock_project_id = project.id
        return project

    def action_view_stock_project(self):
        self.ensure_one()
        projects = self.stock_project_id | self.order_line.stock_task_id.project_id
        if not projects:
            return {'type': 'ir.actions.act_window_close'}
        if len(projects) == 1:
            return {
                'type': 'ir.actions.act_window',
                'res_model': 'project.project',
                'view_mode': 'form',
                'res_id': projects.id,
                'target': 'current',
            }
        return {
            'type': 'ir.actions.act_window',
            'name': _('Projects'),
            'res_model': 'project.project',
            'view_mode': 'kanban,tree,form',
            'domain': [('id', 'in', projects.ids)],
            'target': 'current',
        }


class SaleOrderLine(models.Model):
    _inherit = 'sale.order.line'

    stock_project_id = fields.Many2one(
        'project.project', string="Stock Project", copy=False, index='btree_not_null',
        help="Project in which the Stock Task of this order line was created.")
    stock_task_id = fields.Many2one(
        'project.task', string="Stock Task", copy=False, index='btree_not_null',
        help="Task automatically generated for this order line. Used to prevent "
             "duplicated tasks when the order is confirmed again.")

    def _stock_task_name(self):
        self.ensure_one()
        return "%s - %s %s" % (
            self.product_id.display_name,
            '%g' % self.product_uom_qty,
            self.product_uom.name or '',
        )

    def _stock_get_product_project(self):
        """ Project set on the product (mode 'Task'), matching the SO company. """
        self.ensure_one()
        product = self.product_id.with_company(self.company_id)
        project = product.stock_project_id
        if not project:
            raise UserError(_(
                "The product %s is configured to create a Task on order, but no "
                "Stock Project is set on the product.",
                self.product_id.display_name,
            ))
        if project.company_id and project.company_id != self.company_id:
            raise UserError(_(
                "The Stock Project of product %s belongs to company %s, but this "
                "Sales Order belongs to company %s.",
                self.product_id.display_name,
                project.company_id.name or _('Undefined'),
                self.company_id.name or _('Undefined'),
            ))
        return project

    def _stock_create_task(self, project):
        self.ensure_one()
        if self.stock_task_id:
            return self.stock_task_id
        task = self.env['project.task'].sudo().create({
            'name': self._stock_task_name(),
            'project_id': project.id,
            'partner_id': self.order_id.partner_id.id,
            'company_id': project.company_id.id or self.company_id.id,
        })
        self.stock_task_id = task.id
        return task